### PR TITLE
Update for 1.1

### PR DESCRIPTION
**Pull request by TheDiamondYT1**

### CODE REVIEW

**Comment by dktapps** [comment]
Could you run [this](https://github.com/dktapps/mcpe-default-addon/blob/master/fix_stupid_formatting.php) in the repository root please?

**Comment by TheDiamondYT1** [comment]
@dktapps Done.

**Comment by dktapps** [comment]
Thanks. I'll review this properly later when I have time.

**Comment by TheDiamondYT1** [comment]
Bump

**Comment by dktapps** [comment]
Thanks for the reminder, I'd forgotten about this.

**Pull request merged**
